spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Testus

    username: postgres
    password: aternosru123

    driver-class-name: org.postgresql.Driver

    session:
        store-type: none

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

      properties:
        hibernate:
          format_sql: true

      database-platform: org.hibernate.dialect.PostgreSQLDialect